---
title: "Assignment 04"
author: "Philip Anderson"
date: "November 12, 2017"
output:
  pdf_document: default
  html_document:
    df_print: paged
email: panders2@tamu.edu
---

# Preliminaries

```{r}
#import third-party modules
library("caret")
library("MASS")
library("tidyverse")

```

```{r}
# import the data
hof <- read.csv("/Users/Philip/Schools/TAMU/STAT_636/homework/hof_data.csv")
names(hof) <- tolower(names(hof))

```

```{r}
# manipulate the data
# we are only keeping a handful of predictors - limit down to these now
hof2 <- hof %>%
  dplyr::select(id, name, hof, h, hr, rbi, avg, slg, obp)

# create a numeric indicator for HOF status
table(hof2$hof) / length(hof2$hof) # check
# getting into the hall of fame appears to be a relatively rare event

```


# Linear Discriminant Analysis

```{r}
lda1 <- MASS::lda(hof ~ h + hr + rbi + avg + slg + obp
                  , data=hof2
                  , prior=c(0.5, 0.5) # non-informative prior
                  , CV=TRUE
                  )

```
